### ISSUE TITLE
최신 리스트 조회 cursorId 관련 문제

### ISSUE THREAD

**Issue by kdkdhoho** [8-Sprinters/ListyWave-back#216]
### 🐞 버그 설명

<img width="597" alt="image" src="https://github.com/8-Sprinters/ListyWave-back/assets/66300965/2ca1e7c4-6be4-48a3-a15f-fba26938f2bc">

비회원이 최신 리스트 10개 조회하면 첫 Slice에는 list_id=158부터 list_id=73 까지 정상적으로 나옵니다.
하지만 현재 where 절에 `listIdLt(cursorId)` 가 포함되어 있어 다음 Slice에서는 id가 73보다 작은 List만이 조회됩니다.

![image](https://github.com/8-Sprinters/ListyWave-back/assets/66300965/c24875b4-295c-4c6c-b621-3c03f11190c9)
<img width="380" alt="image" src="https://github.com/8-Sprinters/ListyWave-back/assets/66300965/a793a48a-c5e2-40f3-a133-82cf787f7249">

### ✅ 예상 결과

리스트가 순서대로 조회된다.

### ❗ 실제 결과

첫 Slice에서는 정상이지만 다음 Slice부터 순서대로 나오지 않는다

### 💻 버그 시뮬레이션

-

### 🙋🏻 More

- https://github.com/8-Sprinters/ListyWave-front/issues/139

**Comment by pparkjs** [comment]
아... 이게 정책이 최신리스트 가져오는게 updated 일자 기준으로 정렬해서 가져오는 거라 그런지 cursorId를 리스트번호로 하니까 일치하지가 않네요 ㅠㅠ cursorId를 updatedDate로 해봐야 겠네요.. 집가서 수정해보겠습니다!

**Comment by kdkdhoho** [comment]
@pparkjs 제가 수정하겠습니다! cursor 값을 updatedDate로 받고 `list.updatedDate.lt(cursorUpdatedDate)` 로 하면 되겠죠?

**Comment by pparkjs** [comment]
@kdkdhoho 그러면 될 거 같습니다!
