### ISSUE TITLE
내 피드 공개 / 비공개 api의 isPublic 정책을 바꾼다.

### ISSUE THREAD

**Issue by pparkjs** [8-Sprinters/ListyWave-back#289]
# Description
기존 요청 body에 가져가는 isPublic은  현재 상태를 가져가서 바꾸는 방식이였는데,
이를 바꾸고 싶은 상태를 가져가는 것으로 변경한다.

ex) 1번 리스트가 공개인 경우
ASIS
 - 공개 리스트를 비공개로 설정하려는 경우 기존에는  요청 body에 현재 상태(isPublic = true)를 보내서 API측에서 현재 상태에서 반대로(isPublic = false) 바꾸는 방식으로 진행함 
 그런데 이 방식은 프론트측에서 리스트 상세에서 받는 isPublic과 뭔가 매칭이 안되서 햇갈린다고 통일을 요청함

TOBE
- 해당 리스트가 공개일때 이를 비공개로 바꾸고자 할때 isPublic = false로 보냄( 내가 바꾸고 싶은 상태를 보내는 방식)  

# TODO
- [x] isPublic 정책 변경하기.

# 관련 Issue
- #192

**Comment by kdkdhoho** [comment]
Description만 보고는 어떤 작업인지 잘 이해되지 않네요.. 🥲

**Comment by pparkjs** [comment]
@kdkdhoho 
Description을 좀 더 이해가 되도록 수정 했습니다! 보시고 이해안되시면 다시 말씀해주세요!

**Comment by kdkdhoho** [comment]
@pparkjs 
아하! 이제 이해됐습니다! 굿이에요 굿~ 👍
